// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineVerilog.Context;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(VeronContext))]
    [Migration("20250921115641_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7158ab2a-f77f-45cb-810b-b11af8ff7aab",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "9fa52e96-9d65-4a4e-9b0c-47c778d352cc",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8158ab2a-f77f-43cb-820b-b22af8ff7aab",
                            RoleId = "7158ab2a-f77f-45cb-810b-b11af8ff7aab"
                        },
                        new
                        {
                            UserId = "afa52e96-9d75-4a4e-9b0c-47c888d352cc",
                            RoleId = "9fa52e96-9d65-4a4e-9b0c-47c778d352cc"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineVerilog.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestBench")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imagePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Examples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Креирај логичко коло без улаза и са једним излазом који враћа нулу.",
                            Header = "Нула",
                            Section = "Основе",
                            TestBench = "module testbench;\r\n  wire y;\r\n\r\n  topmodule tm(y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ty\");\r\n\r\n		# 100; \r\n		if ( y == 0 ) \r\n			$display (\"  PASS  \\t%d\", y);\r\n		else\r\n			$display (\"  FAIL \\t%d\", y);\r\n\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 2,
                            Body = "За разлику од физичких жица у Верилогу информација тече само у једном смеру, обично од једног извора ка потрошачу. Додела вредности се ради десно ка лево, вредност сигнала са десне стране се емитује на жицу са леве стране. У Верилогу додела није једнократни догађај него је \"континуална\" јер се додела одвија непрестано чак и ако се вредност са десне стране промени. \r\nПортови на модулу такође имају свој смер (обично улаз или излаз). Улазни порт је покренут нечим ван модула, док излазни порт покреће нешто споља. \r\nПотребно је да се креирати модул са јендним улазом и једним излазом који ће се понапати као жица.",
                            Header = "Жица",
                            Section = "Основе",
                            TestBench = "module testbench;\r\n  reg a;\r\n  wire y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a,y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\s-\\sy\");\r\n\r\n		a = 1; # 100; \r\n		if ( y == 1 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL \\t%d - %d\",a,y);\r\n\r\n		a = 0; # 100; \r\n		if ( y == 0 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL  \\t%d - %d\",a,y);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/zica.png"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Креирајте модул са 3 улаза и 4 излаза који се понаша као жице које праве ове везе:\r\na -> w\r\nb -> x\r\nb -> y\r\nc -> z",
                            Header = "Четири жице",
                            Section = "Основе",
                            TestBench = "module testbench;\r\n  reg a, b, c;\r\n  wire w, x, y, z;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, c, w, x, y, z);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\sb\\sc\\s-\\sw, x, y, z\");\r\n\r\n		a = 0; b = 0; c = 0; # 100; \r\n		if (w ==0 && x==0 && y == 0 &&  z==0) \r\n			$display (\"  PASS  \\t%d %d %d- %d %d %d %d\", a, b, c, w, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d- %d %d %d %d\", a, b, c, w, x, y, z);\r\n\r\n		a = 0; b = 1; c = 0; # 100; \r\n		if (w ==0 && x==1 && y == 1 &&  z==0) \r\n			$display (\"  PASS  \\t%d %d %d- %d %d %d %d\", a, b, c, w, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d- %d %d %d %d\", a, b, c, w, x, y, z);\r\n\r\n                a = 1; b = 1; c = 1; # 100; \r\n		if (w ==1 && x==1 && y == 1 &&  z==1) \r\n			$display (\"  PASS  \\t%d %d %d- %d %d %d %d\", a, b, c, w, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d- %d %d %d %d\", a, b, c, w, x, y, z);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/4zice.png"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Креирајте модул који имплементира не логичко коло. Уколико је 1 на улазу на излазу треба да добијемо 0 и уколико је 0 на излазу треба да добијемо 1.\r\n",
                            Header = "Негација",
                            Section = "Логичка кола",
                            TestBench = "module testbench;\r\n  reg a;\r\n  wire y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a,y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\s-\\sy\");\r\n\r\n		a = 1; # 100; \r\n		if ( y == 0 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL \\t%d - %d\",a,y);\r\n\r\n		a = 0; # 100; \r\n		if ( y == 1 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL  \\t%d - %d\",a,y);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/ne-kolo.png"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Креаирати модул који имлементира и логичко коло.",
                            Header = "И коло",
                            Section = "Логичка кола",
                            TestBench = "module testbench;\r\n  reg a, b;\r\n  wire y;\r\n\r\n  topmodule tm(a, b, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b - y\");\r\n\r\n		a = 0; b = 0 # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 0; b = 1 # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 1; b = 0 # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n               	\r\n                a = 1; b = 1 # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/i-kolo.png"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Креаирати модул који имлементира или логичко коло.",
                            Header = "Или коло",
                            Section = "Логичка кола",
                            TestBench = "module testbench;\r\n  reg a, b;\r\n  wire y;\r\n\r\n  topmodule tm(a, b, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b - y\");\r\n\r\n		a = 0; b = 0; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 0; b = 1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 1; b = 0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n               	\r\n                a = 1; b = 1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/ili-kolo.png"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Креаирати модул који имлементира ни логичко коло.",
                            Header = "Ни коло",
                            Section = "Логичка кола",
                            TestBench = "module testbench;\r\n  reg a, b;\r\n  wire y;\r\n\r\n  topmodule tm(a, b, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b - y\");\r\n\r\n		a = 0; b = 0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 0; b = 1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 1; b = 0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n               	\r\n                a = 1; b = 1; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/ni-kolo.png"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Креаирати модул који имлементира ексклузивно или коло логичко коло.",
                            Header = "Ексклузивно или коло",
                            Section = "Логичка кола",
                            TestBench = "module testbench;\r\n  reg a, b;\r\n  wire y;\r\n\r\n  topmodule tm(a, b, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b - y\");\r\n\r\n		a = 0; b = 0; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 0; b = 1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n\r\n		a = 1; b = 0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n               	\r\n                a = 1; b = 1; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d - %d \", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/xor-kolo.png"
                        },
                        new
                        {
                            Id = 9,
                            Body = "Креирати модул који ће изледати као на слици испод...",
                            Header = "Комбинација",
                            Section = "Комбинација",
                            TestBench = "module testbench;\r\n  reg a, b, c;\r\n  wire out;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, c, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - y\");\r\n\r\n		a = 0;b=0;c=0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d - %d\", a, b, c, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, c, y);    \r\n               \r\n		a = 1;b=0;c=0; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d  %d %d - %d\", a, b, c, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, c, y); \r\n                  \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/logicka-sema-2.png"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Креирати модул који прима два двобитна улаза и на излаз даје 1 уколико су улази једнаки.",
                            Header = "Двобитно поређење",
                            Section = "Комбинација",
                            TestBench = "module testbench;\r\n  reg[1:0] a, b;\r\n  wire y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b - y\");\r\n\r\n		a = 1; b=1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d  - %d\", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);    \r\n               \r\n              	a = 0; b=1; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d  - %d\", a, b, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d\", a, b, y);         \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 11,
                            Body = "Креирати модул који ће да контролира рад једног клима уређаја при чему ће активирати по потреби грејање, хлађење или вентилатор. Модул треба да има четири једнобитна улаза (prevruce, prehladno, mod, ukljucen_ventilator) и три једнобитна излаза (grejanje, hladjenje, ventilator). \r\nУколико је mod 1 и кад је prehladno 1 потребно је да се укључи grejanje а да се hladjenje угаси. Ако је mod 1 и prevruce је 1 потребно је да се укључи hladjenje а да се угаси grejanje. Ако је grejanje или hladjenje активно потребно је да се и ventilator укључи због циркулације ваздуха. За активирање ventilator-а се такође користи улаз ukljucen_ventilator.",
                            Header = "Термостат",
                            Section = "Комбинација",
                            TestBench = "module testbench;\r\n  reg a, b, c, d;\r\n  wire x, y, z;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, c, d, x, y, z);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b c d - x y z\");\r\n\r\n		a = 0; b = 1; c = 0; d=0;# 100; \r\n		if (x==0 && y == 1 &&  z==1) \r\n			$display (\"  PASS  \\t%d %d %d %d - %d %d %d\", a, b, c, d, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d %d %d\", a, b, c, d, x, y, z);\r\n\r\n		a = 1; b = 0; c = 1; d=0;# 100; \r\n		if (x==0 && y == 0 &&  z==0) \r\n			$display (\"  PASS  \\t%d %d %d %d - %d %d %d\", a, b, c, d, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d %d %d\", a, b, c, d, x, y, z);\r\n\r\n		a = 0; b = 0; c = 0; d=1;# 100; \r\n		if (x==0 && y == 0 &&  z==1) \r\n			$display (\"  PASS  \\t%d %d %d %d - %d %d %d\", a, b, c, d, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d %d %d\", a, b, c, d, x, y, z);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 12,
                            Body = "Потребно је креирати модул који ће да прими тробитни улаз и да на излаз да колико јединица има у улазном сигналу.",
                            Header = "Поновљене јединице",
                            Section = "Комбинација",
                            TestBench = "module testbench;\r\n  reg[2:0] a;\r\n  wire[1:0] y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - y\");\r\n\r\n		a = 1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d\", a, y);    \r\n               \r\n              	a = 3; # 100; \r\n		if (y == 2) \r\n			$display (\"  PASS  \\t%d  - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d\", a, y);  \r\n\r\n               a = 7; # 100; \r\n		if (y == 3) \r\n			$display (\"  PASS  \\t%d  - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d\", a, y);          \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 13,
                            Body = "Креирати модул који ће да 16 битни код са тастатуре који прима на улаз дешифрирати и вратити на излаз која је стрелица у питање.\r\nИзлази ће бити 4 једнобитне вредности лево, десно, доле и горе.",
                            Header = "Тастатура",
                            Section = "Комбинација",
                            TestBench = "module testbench;\r\n  reg[15:0] a;\r\n  wire gore, desno, dole, levo;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, gore, desno, dole, levo);\r\n  \r\n	initial\r\n	begin\r\n		$displadole (\"RESULT\\ta - gore desno dole levo\");\r\n\r\n		a = 16'he075;# 100; \r\n		if (gore == 1 && desno==0 && dole == 1 &&  levo==0) \r\n			$displadole (\"  PASS  \\t%d  - %d %d %d %d\", a, gore, desno, dole, levo);\r\n		else \r\n			$displadole (\"  FAIL \\t%d - %d %d %d %d\", a, gore, desno, dole, levo);\r\n\r\n		a = 16'he074;# 100; \r\n		if (gore == 0 && desno==1 && dole == 1 &&  levo==0) \r\n			$displadole (\"  PASS  \\t%d  - %d %d %d %d\", a, gore, desno, dole, levo);\r\n		else \r\n			$displadole (\"  FAIL \\t%d - %d %d %d %d\", a, gore, desno, dole, levo);\r\n\r\n		a = 16'he072;# 100; \r\n		if (gore == 0 && desno==0 && dole == 1 &&  levo==0) \r\n			$displadole (\"  PASS  \\t%d  - %d %d %d %d\", a, gore, desno, dole, levo);\r\n		else \r\n			$displadole (\"  FAIL \\t%d - %d %d %d %d\", a, gore, desno, dole, levo);\r\n\r\n        a = 16'he06b;# 100; \r\n		if (gore == 0 && desno==0 && dole == 0 &&  levo==1) \r\n			$displadole (\"  PASS  \\t%d  - %d %d %d %d\", a, gore, desno, dole, levo);\r\n		else \r\n			$displadole (\"  FAIL \\t%d - %d %d %d %d\", a, gore, desno, dole, levo);\r\n	end\r\n	  \r\n  //enabling the goreave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/tastatura.png"
                        },
                        new
                        {
                            Id = 14,
                            Body = "Креирати 2 - 1 мултиплексер...",
                            Header = "Мултиплексер 2-1",
                            Section = "Плексери",
                            TestBench = "module testbench;\r\n  reg a, b, sel;\r\n  wire y;\r\n\r\n  topmodule tm(a, b, sel, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b sel- y\");\r\n\r\n		a = 1; b = 0; sel=0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d %d - %d\", a, b, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, sel, y);\r\n\r\n		a = 1; b = 0; sel=1; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d %d %d - %d\", a, b, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, sel, y);		\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 15,
                            Body = "Креирати модул мултиплексер 2 на 1, који има  два 16 битна улаза, један једнобитни улаз селекције и један излаз.",
                            Header = "16-Битни мултиплексер",
                            Section = "Плексери",
                            TestBench = "module testbench;\r\n  reg[15:0] a, b;\r\n  reg sel;\r\n  wire[15:0]  y;\r\n\r\n  topmodule tm(a, b, sel, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b sel- y\");\r\n\r\n		a = 7; b = 3; sel=0; # 100; \r\n		if (y == 7) \r\n			$display (\"  PASS  \\t%d %d %d - %d\", a, b, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, sel, y);\r\n\r\n		a = 7; b = 3; sel=1; # 100; \r\n		if (y == 3) \r\n			$display (\"  PASS  \\t%d %d %d - %d\", a, b, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, sel, y);		\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 16,
                            Body = "Креирати модул мултиплексер 4 на 1, који ће имати четри тробитних улаза, један двотни улаз за селекцију и један излаз.  ",
                            Header = "Мултиплексер 4-1",
                            Section = "Плексери",
                            TestBench = "module testbench;\r\n  reg[2:0] a, b, c ,d;\r\n  reg[1:0]  sel;\r\n  wire[2:0]  y;\r\n\r\n  topmodule tm(a, b, c, d, sel, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b sel- y\");\r\n\r\n		a = 7; b = 5; c=3; d=1; sel=0; # 100; \r\n		if (y == 7) \r\n			$display (\"  PASS  \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n\r\n		a = 7; b = 5; c=3; d=1; sel=1; # 100; \r\n		if (y == 5) \r\n			$display (\"  PASS  \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n\r\n		a = 7; b = 5; c=3; d=1; sel=2; # 100; \r\n		if (y == 3) \r\n			$display (\"  PASS  \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n\r\n		a = 7; b = 5; c=3; d=1; sel=3; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d %d - %d\", a, b, c, d, sel, y);	\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 17,
                            Body = "Креирати модул који ће престављати приоритентни енкодер. Приоритетни енкодер на улазу прима четворобитну вредност и на излазу даје локацију навишег бита, што ће бити величине два бита.",
                            Header = "Приоритетни енкодер",
                            Section = "Плексери",
                            TestBench = "module testbench;\r\n  reg[3:0] a;\r\n  wire[1:0]  y;\r\n\r\n  topmodule tm(a, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - y\");\r\n\r\n		a = 1; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d  - %d\", a, y);\r\n\r\n		a = 2; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d  - %d\", a, y);\r\n\r\n		a = 4; # 100; \r\n		if (y == 2) \r\n			$display (\"  PASS  \\t%d - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d  - %d\", a, y);\r\n\r\n		a = 8; # 100; \r\n		if (y == 3) \r\n			$display (\"  PASS  \\t%d - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d  - %d\", a, y);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 18,
                            Body = "Креирати модул полусабирач, који сабира два једнобитна улаза и на излаз даје  једнобитну суму и пренос.",
                            Header = "Полусабирач",
                            Section = "Аритметика",
                            TestBench = "module testbench;\r\n  reg a, b;\r\n  wire y, cout;\r\n\r\n  topmodule tm(a, b, y, cout);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b - y, cout\");\r\n\r\n		a = 0; b = 0; # 100; \r\n		if (y == 0 && cout == 0) \r\n			$display (\"  PASS  \\t%d %d - %d %d\", a, b, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d %d\", a, b, y, cout);\r\n\r\n		a = 0; b = 1; # 100; \r\n		if (y == 1 && cout == 0) \r\n			$display (\"  PASS  \\t%d %d - %d %d\", a, b, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d %d\", a, b, y, cout);\r\n\r\n		a = 1; b = 1; # 100; \r\n		if (y == 0 && cout == 1) \r\n			$display (\"  PASS  \\t%d %d - %d %d\", a, b, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d - %d %d\", a, b, y, cout);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 19,
                            Body = "Креирати модул сабирач, који сабира три једнобитна улаза (a, b, cin) и на излаз даје  једнобитну суму и пренос.",
                            Header = "Сабирач",
                            Section = "Аритметика",
                            TestBench = "module testbench;\r\n  reg a, b, cin;\r\n  wire y, cout;\r\n\r\n  topmodule tm(a, b, cin, y, cout);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b cin - y, cout\");\r\n\r\n		a = 0; b = 0; cin=0; # 100; \r\n		if (y == 0 && cout == 0) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n\r\n		a = 1; b = 0; cin=0; # 100; \r\n		if (y == 1 && cout == 0) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n\r\n		a = 1; b = 1; cin=0; # 100; \r\n		if (y == 0 && cout == 1) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n\r\n               	a = 1; b = 1; cin=1; # 100; \r\n		if (y == 1 && cout == 1) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 20,
                            Body = "Креирати модул сабирач, који сабира два четворобинта улаза (a, b), један једнобитно улаз (cin) и на излаз даје четворобитну суму и пренос.",
                            Header = "Сабирач4",
                            Section = "Аритметика",
                            TestBench = "module testbench;\r\n  reg[3:0] a, b;\r\n  reg cin;\r\n  wire[3:0] y, cout;\r\n\r\n  topmodule tm(a, b, cin, y, cout);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b cin - y, cout\");\r\n\r\n		a = 0; b = 0; cin=0; # 100; \r\n		if (y == 0 && cout == 0) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n\r\n		a = 1; b = 0; cin=0; # 100; \r\n		if (y == 1 && cout == 0) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n\r\n		a = 1; b = 1; cin=0; # 100; \r\n		if (y == 0 && cout == 1) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n\r\n               	a = 4'b1110; b = 1; cin=1; # 100; \r\n		if (y == 1 && cout == 1) \r\n			$display (\"  PASS  \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d %d\", a, b, cin, y, cout);\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 21,
                            Body = "Креирати модул који ће имплементирати шему са слике.",
                            Header = "КМ1",
                            Section = "Карнове мапе",
                            TestBench = "module testbench;\r\n  reg a, b, c;\r\n  wire y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, c, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - y\");\r\n\r\n		a = 0;b=0;c=0; # 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d  %d %d - %d\", a, b, c, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, c, y);    \r\n               \r\n		a = 1;b=0;c=0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d - %d\", a, b, c, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, c, y); \r\n\r\n		a = 0;b=1;c=1; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d - %d\", a, b, c, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, c, y);\r\n\r\n		a = 1;b=1;c=0; # 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d - %d\", a, b, c, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d - %d\", a, b, c, y);\r\n                  \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/KM1.png"
                        },
                        new
                        {
                            Id = 22,
                            Body = "Креирати модул који ће имплементирати шему са слике.",
                            Header = "КМ2",
                            Section = "Карнове мапе",
                            TestBench = "module testbench;\r\n  reg a, b, c, d;\r\n  wire out;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, c, d, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta b c d - y\");\r\n\r\n		a = 0;b=0;c=0;d=0;# 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d %d - %d\", a, b, c, d, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d\", a, b, c, d, y);    \r\n               \r\n		a = 1;b=0;c=1;d=1;# 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d %d - %d\", a, b, c, d, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d\", a, b, c, d, y);  \r\n\r\n		a = 0;b=1;c=0;d=1;# 100; \r\n		if (y == 0) \r\n			$display (\"  PASS  \\t%d  %d %d %d - %d\", a, b, c, d, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d\", a, b, c, d, y);  \r\n\r\n		a = 0;b=0;c=1;d=0;# 100; \r\n		if (y == 1) \r\n			$display (\"  PASS  \\t%d  %d %d %d - %d\", a, b, c, d, y);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d %d - %d\", a, b, c, d, y);  \r\n                  \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/KM2.png"
                        },
                        new
                        {
                            Id = 23,
                            Body = "Креирати модул који ће на улаз да добије тробитни улаз, а на излаз ће вратити три једнобитна излаза.",
                            Header = "Вектор",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[2:0] a;\r\n  wire x, y, z;\r\n\r\n  topmodule tm(a, x, y, z);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - x, y, z\");\r\n\r\n		a = 5; # 100; \r\n		if (x == 1 && y == 0 && z == 1) \r\n			$display (\"  PASS  \\t%d - %d %d %d\", a, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d  -  %d %d %d\", a, x, y, z);\r\n\r\n		a = 2; # 100; \r\n		if (x == 0 && y == 1 && z == 0) \r\n			$display (\"  PASS  \\t%d - %d %d %d\", a, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d  -  %d %d %d\", a, x, y, z);		\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/vektor.png"
                        },
                        new
                        {
                            Id = 24,
                            Body = "Креирати модул који на улазу прима 16 битни вектор а на излазу даје два 8 битна вектора.",
                            Header = "Полу вектор",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[15:0] a;\r\n  wire[7:0] x, y;\r\n\r\n  topmodule tm(a, x, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - x, y\");\r\n\r\n		a = 16'hacbf; # 100; \r\n		if (x == 8'hac && y == 8'hbf) \r\n			$display (\"  PASS  \\t%d - %d %d\", a, x, y);\r\n		else \r\n			$display (\"  FAIL \\t%d  -  %d %d\", a, x, y);\r\n			\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/poluvektor.png"
                        },
                        new
                        {
                            Id = 25,
                            Body = "Креирати модул где имамо 32 битни улаз који се састоји од 4 осмобитне речи и на излазу враћа исте те 4 речи али у обрнутом редоследу. Ево пример:\r\n11111111222222223333333344444444 => 44444444333333332222222211111111 ",
                            Header = "Обрнуте речи",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[31:0] a;\r\n  wire[31:0] x;\r\n\r\n  topmodule tm(a, x);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta - x\");\r\n\r\n		a = 32'h12345678; # 100; \r\n		if (x == 32'h78563412) \r\n			$display (\"  PASS  \\t%d - %d\", a, x);\r\n		else \r\n			$display (\"  FAIL \\t%d  -  %d\", a, x);\r\n			\r\n	end\r\n	  \r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 26,
                            Body = "Креирати модул који добија на улаз тробитну вредност и потребно је да је на излаз да врати три једнобитна излаза (a, o, x).\r\no излаз а ће бити резултат тробитног и кола\r\nо излаз о ће бити резултат тробитног или кола\r\nо излаз х ће бити резултат тробитног ексклузивног или коло",
                            Header = "Логичка кола",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[2:0] a;\r\n  wire x, y, z;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, x, y, z);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\sb\\sc\\s- x, y, z\");\r\n\r\n		a = 5; # 100; \r\n		if ( x==0 && y == 1 &&  z==0) \r\n			$display (\"  PASS  \\t%d - %d %d %d\", a, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d %d %d\", a, x, y, z);\r\n\r\n		a = 7; # 100; \r\n		if ( x==1 && y == 1 &&  z==1) \r\n			$display (\"  PASS  \\t%d - %d %d %d\", a, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d %d %d\", a, x, y, z);              \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 27,
                            Body = "Креирати модул који извршити пребацивање три петобитна улаза у четири четворобитна излаза.",
                            Header = "Спајање",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[4:0] a, b, c;\r\n  wire[3:0] w, x, y, z;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, b, c, w, x, y, z);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\sb\\sc\\s- w, x, y, z\");\r\n\r\n		a = 5'b10101;b=5'b01010;c=5'b10101; # 100; \r\n		if (w == 4'b1010 && x==4'b1010 && y == 4'b1010 &&  z==4'b1011) \r\n			$display (\"  PASS  \\t%d %d %d  - %d %d %d %d\", a, b, c, w, x, y, z);\r\n		else \r\n			$display (\"  FAIL \\t%d %d %d  - %d %d %d %d\", a, b, c, w, x, y, z);           \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/spajanje.png"
                        },
                        new
                        {
                            Id = 28,
                            Body = "Креирати модул који улазну осмобитну вредност баци на излазу са обрнутом редоследу.\r\n12345678 => 87654321",
                            Header = "Обрнут редослед",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[7:0]a;\r\n  wire[7:0] y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta- y\");\r\n\r\n		a = 8'b10101010; # 100; \r\n		if (y == 8'b01010101) \r\n			$display (\"  PASS  \\t%d  - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d\", a, y);           \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 29,
                            Body = "Креирати модул који има осмобитни улаз и на излаз даје улазну вредност која је проширена да буде тридесетдвобитна. Улазна вредност је проширена тако што је седми бит дуплициран 24 пута и онда следи осмобитни улаз.",
                            Header = "Проширивање",
                            Section = "Вектори",
                            TestBench = "module testbench;\r\n  reg[7:0]a;\r\n  wire[31:0] y;\r\n\r\n  //Design Instance\r\n  topmodule tm(a, y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta- y\");\r\n\r\n		a = 8'hac; # 100; \r\n		if (y == 32'hffffffac) \r\n			$display (\"  PASS  \\t%d  - %d\", a, y);\r\n		else \r\n			$display (\"  FAIL \\t%d - %d\", a, y);           \r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        });
                });

            modelBuilder.Entity("OnlineVerilog.Models.SolvedExample", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExampleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ExampleId");

                    b.HasIndex("ExampleId");

                    b.ToTable("SolvedExamples");
                });

            modelBuilder.Entity("OnlineVerilog.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8158ab2a-f77f-43cb-820b-b22af8ff7aab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4468783f-d93f-4f9b-bcb9-bad82195baad",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHIk+J96/+iF5loHeF1tqKWnMVpw899Z6yWrv8QKInXMRNjBqIlqwY/v3pLfmYy6eA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a26cd955-dc08-47c1-a55b-2f08c0219be4",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "afa52e96-9d75-4a4e-9b0c-47c888d352cc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bae5ca52-4a63-41f4-b6e7-045c7602b63e",
                            Email = "toni@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "toni",
                            LockoutEnabled = false,
                            NormalizedEmail = "TONI@GMAIL.COM",
                            NormalizedUserName = "TONI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEHEwzeGRHOwAds+lD4zL74s2hAVZIXRBSI373Gjye7cGx31RLhDQjLep25UeCZZxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f09f74f1-c35d-4cb1-8a55-545a0402b307",
                            TwoFactorEnabled = false,
                            UserName = "toni@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineVerilog.Models.SolvedExample", b =>
                {
                    b.HasOne("OnlineVerilog.Models.Example", "Example")
                        .WithMany("SolvedByUsers")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineVerilog.Models.User", "SolvedByUser")
                        .WithMany("SolvedExamples")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Example");

                    b.Navigation("SolvedByUser");
                });

            modelBuilder.Entity("OnlineVerilog.Models.Example", b =>
                {
                    b.Navigation("SolvedByUsers");
                });

            modelBuilder.Entity("OnlineVerilog.Models.User", b =>
                {
                    b.Navigation("SolvedExamples");
                });
#pragma warning restore 612, 618
        }
    }
}
