// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineVerilog.Context;

#nullable disable

namespace OnlineVerilog.Migrations
{
    [DbContext(typeof(VeronContext))]
    partial class VeronContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7158ab2a-f77f-45cb-810b-b11af8ff7aab",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "9fa52e96-9d65-4a4e-9b0c-47c778d352cc",
                            Name = "user",
                            NormalizedName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8158ab2a-f77f-43cb-820b-b22af8ff7aab",
                            RoleId = "7158ab2a-f77f-45cb-810b-b11af8ff7aab"
                        },
                        new
                        {
                            UserId = "afa52e96-9d75-4a4e-9b0c-47c888d352cc",
                            RoleId = "9fa52e96-9d65-4a4e-9b0c-47c778d352cc"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineVerilog.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestBench")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imagePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Examples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Креирај логичко коло без улаза и са једним излазом који враћа нулу.",
                            Header = "Нула",
                            Section = "Основе",
                            TestBench = "module testbench;\r\n  wire y;\r\n\r\n  topmodule tm(y);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\s-\\sy\");\r\n\r\n		# 100; \r\n		if ( y == 0 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL \\t%d - %d\",a,y);\r\n\r\n		# 100; \r\n		if ( y == 1 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL  \\t%d - %d\",a,y);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 2,
                            Body = "За разлику од физичких жица у Верилогу информација тече само у једном смеру, обично од једног извора ка потрошачу. Додела вредности се ради десно ка лево, вредност сигнала са десне стране се емитује на жицу са леве стране. У Верилогу додела није једнократни догађај него је \"континуална\" јер се додела одвија непрестано чак и ако се вредност са десне стране промени. \r\nПортови на модулу такође имају свој смер (обично улаз или излаз). Улазни порт је покренут нечим ван модула, док излазни порт покреће нешто споља. \r\nПотребно је да се креирати модул са јендним улазом и једним излазом који ће се понапати као жица.",
                            Header = "Жица",
                            Section = "Основе",
                            TestBench = "module testbench;\r\n  reg a;\r\n  wire y;\r\n\r\n  //Design Instance\r\n  topmodule tm(y,a);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\s-\\sy\");\r\n\r\n		a = 1; # 100; \r\n		if ( y == 1 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL \\t%d - %d\",a,y);\r\n\r\n		a = 0; # 100; \r\n		if ( y == 0 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL  \\t%d - %d\",a,y);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/zica.png"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Креирајте модул са 3 улаза и 4 излаза који се понаша као жице које праве ове везе:\r\nа -> w\r\nб -> x\r\nб -> y\r\nц -> z",
                            Header = "Четири жице",
                            Section = "Основе",
                            TestBench = "",
                            imagePath = "/uploads/4zice.png"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Креирајте модул који имплементира не логичко коло. Уколико је 1 на улазу на излазу треба да добијемо 0 и уколико је 0 на излазу треба да добијемо 1.\r\n",
                            Header = "Не kоло",
                            Section = "Логичка кола",
                            TestBench = "module testbench;\r\n  reg a;\r\n  wire y;\r\n\r\n  //Design Instance\r\n  topmodule tm(y,a);\r\n  \r\n	initial\r\n	begin\r\n		$display (\"RESULT\\ta\\s-\\sy\");\r\n\r\n		a = 1; # 100; \r\n		if ( y == 0 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL \\t%d - %d\",a,y);\r\n\r\n		a = 0; # 100; \r\n		if ( y == 1 ) \r\n			$display (\"  PASS  \\t%d - %d\",a,y);\r\n		else\r\n			$display (\"  FAIL  \\t%d - %d\",a,y);\r\n	end\r\n	  \r\n  //enabling the wave dump\r\n  initial begin \r\n    $dumpfile(\"dump.vcd\"); $dumpvars;\r\n  end\r\n  \r\nendmodule",
                            imagePath = "/uploads/ne-kolo.png"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Креаирати модул који имлементира и логичко коло.",
                            Header = "И коло",
                            Section = "Логичка кола",
                            TestBench = "",
                            imagePath = "/uploads/i-kolo.png"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Креаирати модул који имлементира или логичко коло.",
                            Header = "Или коло",
                            Section = "Логичка кола",
                            TestBench = "",
                            imagePath = "/uploads/ili-kolo.png"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Креаирати модул који имлементира ни логичко коло.",
                            Header = "Ни коло",
                            Section = "Логичка кола",
                            TestBench = "",
                            imagePath = "/uploads/ni-kolo.png"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Креаирати модул који имлементира ексклузивно или коло логичко коло.",
                            Header = "Ексклузивно или коло",
                            Section = "Логичка кола",
                            TestBench = "",
                            imagePath = "/uploads/xor-kolo.png"
                        },
                        new
                        {
                            Id = 9,
                            Body = "Креирати модул који ће изледати као на слици испод...",
                            Header = "Комбинација 1",
                            Section = "Комбинација",
                            TestBench = "",
                            imagePath = "/uploads/logicka-sema-1.png"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Креирати модул који ће изледати као на слици испод...",
                            Header = "Комбинација 2",
                            Section = "Комбинација",
                            TestBench = "",
                            imagePath = "/uploads/logicka-sema-2.png"
                        },
                        new
                        {
                            Id = 11,
                            Body = "Креирати 2 - 1 мултиплексер...",
                            Header = "Мултиплексер 2-1",
                            Section = "Плексери",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 12,
                            Body = "Креирати модул мултиплексер 2 на 1, који има  два 16 битна улаза, један једнобитни улаз селекције и један излаз.",
                            Header = "16-Битни мултиплексер",
                            Section = "Плексери",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 13,
                            Body = "Креирати модул мултиплексер 8 на 1, који ће имати осам једнобитних улаза, један тробитни улаз за селекцију и једна излаз.  ",
                            Header = "Мултиплексер 8-1",
                            Section = "Плексери",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 14,
                            Body = "Креирати модул који прима два двобитна улаза и на излаз даје 1 уколико су улази једнаки.",
                            Header = "Двобитно поређење",
                            Section = "Комбинација",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 15,
                            Body = "Креирати модул који има два улаза x  и y, излаз z и ће извршити математичку једначину:\r\nz = (x^y) & x",
                            Header = "Математичка једначина",
                            Section = "Основе",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 16,
                            Body = "Креирати модул који ће да контролира рад једног клима уређаја при чему ће активирати по потреби грејање, хлађење или вентилатор. Модул треба да има четири једнобитна улаза (prevruce, prehladno, mod, ukljucen_ventilator) и три једнобитна излаза (grejanje, hladjenje, ventilator). \r\nУколико је mod 1 и кад је prehladno 1 потребно је да се укључи grejanje а да се hladjenje угаси. Ако је mod 1 и prevruce је 1 потребно је да се укључи hladjenje а да се угаси grejanje. Ако је grejanje или hladjenje активно потребно је да се и ventilator укључи због циркулације ваздуха. За активирање ventilator-а се такође користи улаз ukljucen_ventilator.",
                            Header = "Термостат",
                            Section = "Комбинација",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 17,
                            Body = "Потребно је креирати модул који ће да прими тробитни улаз и да на излаз да колико јединица има у улазном сигналу.",
                            Header = "Поновљене јединице",
                            Section = "Комбинација",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 18,
                            Body = "Креирати модул полусабирач, који сабира два једнобитна улаза и на излаз даје  једнобитну суму и пренос.",
                            Header = "Полусабирач",
                            Section = "Аритметика",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 19,
                            Body = "Креирати модул сабирач, који сабира три једнобитна улаза (a, b, cin) и на излаз даје  једнобитну суму и пренос.",
                            Header = "Сабирач",
                            Section = "Аритметика",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 20,
                            Body = "Креирати модул сабирач, који сабира три осмобитна улаза (a, b, cin) и на излаз даје  осмобитну суму и пренос.",
                            Header = "Сабирач8",
                            Section = "Аритметика",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 21,
                            Body = "Креирати модул који ће имплементирати шему са слике.",
                            Header = "КМ1",
                            Section = "Карнове мапе",
                            TestBench = "",
                            imagePath = "/uploads/KM1.png"
                        },
                        new
                        {
                            Id = 22,
                            Body = "Креирати модул који ће имплементирати шему са слике.",
                            Header = "КМ2",
                            Section = "Карнове мапе",
                            TestBench = "",
                            imagePath = "/uploads/KM2.png"
                        },
                        new
                        {
                            Id = 23,
                            Body = "Креирати модул који ће имплементирати шему са слике.",
                            Header = "КМ3",
                            Section = "Карнове мапе",
                            TestBench = "",
                            imagePath = "/uploads/KM3.png"
                        },
                        new
                        {
                            Id = 24,
                            Body = "Креирати модул који ће на улаз да добије тробитни улаз, а на излаз ће вратити три једнобитна излаза.",
                            Header = "Вектор",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = "/uploads/vektor.png"
                        },
                        new
                        {
                            Id = 25,
                            Body = "Креирати модул који на улазу прима 16 битни вектор а на излазу даје два 8 битна вектора.",
                            Header = "Полу вектор",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = "/uploads/poluvektor.png"
                        },
                        new
                        {
                            Id = 26,
                            Body = "Креирати модул где имамо 32 битни улаз који се састоји од 4 осмобитне речи и на излазу враћа исте те 4 речи али у обрнутом редоследу. Ево пример:\r\n11111111222222223333333344444444 => 44444444333333332222222211111111 ",
                            Header = "Обрнуте речи",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 27,
                            Body = "Креирати модул који добија на улаз тробитну вредност и потребно је да је на излаз да врати три једнобитна излаза (a, o, x).\r\no излаз а ће бити резултат тробитног и кола\r\nо излаз о ће бити резултат тробитног или кола\r\nо излаз х ће бити резултат тробитног ексклузивног или коло",
                            Header = "Логичка кола",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 28,
                            Body = "Креирати модул који извршити пребацивање три петобитна улаза у четири четворобитна излаза.",
                            Header = "Спајање",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = "/upload/spajanje.png"
                        },
                        new
                        {
                            Id = 29,
                            Body = "Креирати модул који улазну осмобитну вредност баци на излазу са обрнутом редоследу.\r\n12345678 => 87654321",
                            Header = "Обрнут редослед",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 30,
                            Body = "Креирати модул који има осмобитни улаз и на излаз даје улазну вредност која је проширена да буде тридесетдвобитна. Улазна вредност је проширена тако што је седми бит дуплициран 24 пута и онда следи осмобитни улаз.",
                            Header = "Проширивање",
                            Section = "Вектори",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 31,
                            Body = "Креирати модул који ће престављати приоритентни енкодер. Приоритетни енкодер на улазу прима четворобитну вредност и на излазу даје локацију навишег бита, што ће бити величине два бита.",
                            Header = "Приоритетни енкодер",
                            Section = "Плексери",
                            TestBench = "",
                            imagePath = ""
                        },
                        new
                        {
                            Id = 32,
                            Body = "Креирати модул који ће да 16 битни код са тастатуре који прима на улаз дешифрирати и вратити на излаз која је стрелица у питање.\r\nИзлази ће бити 4 једнобитне вредности лево, десно, доле и горе.",
                            Header = "Тастатура",
                            Section = "Комбинација",
                            TestBench = "",
                            imagePath = "/upload/tastatura.png"
                        });
                });

            modelBuilder.Entity("OnlineVerilog.Models.SolvedExample", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExampleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ExampleId");

                    b.HasIndex("ExampleId");

                    b.ToTable("SolvedExamples");
                });

            modelBuilder.Entity("OnlineVerilog.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8158ab2a-f77f-43cb-820b-b22af8ff7aab",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc19a22e-1955-4b2e-8a1a-ec0d1b0a1f90",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELVbL3KNseiWSqGSGRKoAAf3lTy/DfS3PyFVMcXMGWGJ1OpB8RNZ76q9u/oR7n9Bbw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96d0a083-8b98-49c4-ad11-c7f0c860b963",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "afa52e96-9d75-4a4e-9b0c-47c888d352cc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "571bd2cb-2f50-464e-a4d6-aad327d65d7c",
                            Email = "toni@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "toni",
                            LockoutEnabled = false,
                            NormalizedEmail = "TONI@GMAIL.COM",
                            NormalizedUserName = "TONI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOh9VQKoS2zlX/q5Cl0YyRnnVZIdHclh5iL7hMwGdhg+rUXWD0+JXBqMr5eeeZ+DQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1d50dd0-9d40-4c0a-bdf1-e6979e1acf60",
                            TwoFactorEnabled = false,
                            UserName = "toni@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineVerilog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineVerilog.Models.SolvedExample", b =>
                {
                    b.HasOne("OnlineVerilog.Models.Example", "Example")
                        .WithMany("SolvedByUsers")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineVerilog.Models.User", "SolvedByUser")
                        .WithMany("SolvedExamples")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Example");

                    b.Navigation("SolvedByUser");
                });

            modelBuilder.Entity("OnlineVerilog.Models.Example", b =>
                {
                    b.Navigation("SolvedByUsers");
                });

            modelBuilder.Entity("OnlineVerilog.Models.User", b =>
                {
                    b.Navigation("SolvedExamples");
                });
#pragma warning restore 612, 618
        }
    }
}
